Repository YetAnotherPackageInstaller/YAPI, pull requests merged in 2018-12, with the labels that each got.

#20 Catch url in the packages creation
  scripts/atom.sh
  scripts/eclipseInstaller.sh
  scripts/ideaCom.sh
  scripts/pycharmCom.sh
  scripts/rambox.sh
  scripts/spotify.sh
  scripts/steam.sh
  yapi.py
Labels: enhancement

#18 readme auto updater
  README.md
  readme_updater.py
  scripts/virtualbox.sh
Labels: enhancement

#34 Lighter GUI
  README.md
  cache_manager.py
  requirements.txt
  script_runner.py
  user_interface.py
  yapi.py
Labels: enhancement

#38 Update README.md
  README.md
Labels: enhancement

#46 Slack
  README.md
  scripts/slack.sh
Labels: debian-packages, scripts

#41 YAPI console execution
  README.md
  install.sh
  yapi.sh
Labels: bug

#49 Update .travis.yml to test all packages
  .travis.yml
Labels: enhancement

#40 Docstring
  cache_manager.py
  console_interface.py
  script_runner.py
  yapi.py
Labels: Documentation
